name: Hello

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello!"
      
      - name: Print current date
        run: date

      - name: List current directory contents (long format)
        run: ls -l